/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/environment": {
    /** List the available environments */
    get: operations["environmentsList"];
  };
  "/api/health": {
    /**
     * Basic health check endpoint.
     *
     * This endpoint always returns 200 OK. It is intended for use by load
     * balancers and such that need a basic indication as to whether the server is
     * live.
     */
    get: operations["healthRetrieve"];
  };
}

export interface components {
  schemas: {
    Environment: {
      environmentdPgwireAddress: string;
      environmentdHttpsAddress: string;
      resolvable: boolean;
      /** Format: date-time */
      creationTimestamp: string;
    };
  };
}

export interface operations {
  /** List the available environments */
  environmentsList: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Environment"][];
        };
      };
    };
  };
  /**
   * Basic health check endpoint.
   *
   * This endpoint always returns 200 OK. It is intended for use by load
   * balancers and such that need a basic indication as to whether the server is
   * live.
   */
  healthRetrieve: {
    responses: {
      /** No response body */
      200: unknown;
    };
  };
}

export interface external {}
