/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/environmentassignment": {
    /** List the available environment assignments */
    get: operations["environmentAssignmentsList"];
    /** Create a new environment assignment. */
    post: operations["environmentAssignmentsCreate"];
    /** Destroy an environment assignment. */
    delete: operations["environmentAssignmentsDestroy"];
  };
  "/api/health": {
    /**
     * Basic health check endpoint.
     *
     * This endpoint always returns 200 OK. It is intended for use by load
     * balancers and such that need a basic indication as to whether the server is
     * live.
     */
    get: operations["healthRetrieve"];
  };
}

export interface components {
  schemas: {
    EnvironmentAssignment: {
      cluster: string;
      environmentControllerUrl: string;
    };
    EnvironmentAssignmentRequest: {
      environmentdImageRef?: string;
      /** @default false */
      important?: boolean;
      /** Extra environmentd arguments */
      environmentdExtraArgs?: string[];
    };
  };
}

export interface operations {
  /** List the available environment assignments */
  environmentAssignmentsList: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EnvironmentAssignment"][];
        };
      };
    };
  };
  /** Create a new environment assignment. */
  environmentAssignmentsCreate: {
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["EnvironmentAssignment"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EnvironmentAssignmentRequest"];
      };
    };
  };
  /** Destroy an environment assignment. */
  environmentAssignmentsDestroy: {
    responses: {
      /** No response body */
      202: unknown;
    };
  };
  /**
   * Basic health check endpoint.
   *
   * This endpoint always returns 200 OK. It is intended for use by load
   * balancers and such that need a basic indication as to whether the server is
   * live.
   */
  healthRetrieve: {
    responses: {
      /** No response body */
      200: unknown;
    };
  };
}

export interface external {}
