// constants for recoil keys, to avoid unintentional duplication
/*eslint sort-keys: "error"*/
export default {
  ACTIVE_ENVIRONMENTS: "ACTIVE_ENVIRONMENTS",
  CURRENT_ENVIRONMENT: "CURRENT_ENVIRONMENT",
  ENVIRONMENTS: "ENVIRONMENTS",
  ENVIRONMENT_STATUS: "ENVIRONMENT_STATUS",
  ENVIRONMENT_STATUS_MAP: "ENVIRONMENT_STATUS_MAP",
  HAS_CLOSED_FIRST_REGION_MODAL_MANUALLY:
    "HAS_CLOSED_FIRST_REGION_MODAL_MANUALLY",
  HAS_CREATED_ENVIRONMENT: "HAS_CREATED_ENVIRONMENT",
  ON_FIRST_LOAD: "ON_FIRST_LOAD",
  SHOW_CREATE_REGION_MODAL: "SHOW_CREATE_REGION_MODAL",
};
/*eslint-disable sort-keys*/
