// constants for recoil keys, to avoid unintentional duplication
export default {
  ACTIVE_ENVIRONMENTS: "ACTIVE_ENVIRONMENTS",
  CURRENT_ENVIRONMENT: "CURRENT_ENVIRONMENT",
  ENVIRONMENTS: "ENVIRONMENTS",
  HAS_CREATED_ENVIRONMENT: "HAS_CREATED_ENVIRONMENT",
  HAS_CLOSED_FIRST_REGION_MODAL_MANUALLY:
    "HAS_CLOSED_FIRST_REGION_MODAL_MANUALLY",
  SHOW_CREATE_REGION_MODAL: "SHOW_CREATE_REGION_MODAL",
  STATUS_MAP: "STATUS_MAP",
};
