name: PR
on:
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test --maxWorkers=100%

  e2e-tests:
    runs-on: ubuntu-20.04-16core
    env:
      FRONTEGG_CLIENT_ID: ${{ secrets.E2E_TEST_STAGING_FRONTEGG_CLIENT_ID }}
      FRONTEGG_SECRET_KEY: ${{ secrets.E2E_TEST_STAGING_FRONTEGG_SECRET_KEY }}
    steps:
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: console checkout
        uses: actions/checkout@v3
      - name: cloud checkout
        uses: actions/checkout@v3
        with:
          repository: MaterializeInc/cloud
          ssh-key: ${{ secrets.CLOUD_DEPLOY_KEY }}
          path: ./cloud
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: docker network create kind
      - uses: helm/kind-action@v1.4.0
        with:
          cluster_name: mzcloud
          config: ./cloud/misc/kind/cluster.yaml
          node_image: kindest/node:v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5
      - run: bin/compose pull cli -q
        working-directory: ./cloud
      - name: Kind install
        working-directory: ./cloud
        run: bin/kind-install-all
      - run: kubectl get crd
      - name: Docker compose up
        working-directory: ./cloud
        run: bin/compose up region-controller environment-controller -d --wait
      - run: bin/compose run cli kubectl get crd
        working-directory: ./cloud
        if: always()
      - run: yarn install --frozen-lockfile
      - name: Install playwright browsers
        run: yarn playwright install --with-deps
      - run: nohup yarn start &
        env:
          DEFAULT_STACK: local
      - name: Run e2e tests
        timeout-minutes: 50
        env:
          E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_STAGING_PASSWORD }}
          E2E_FRONTEGG_CLIENT_ID: ${{ secrets.E2E_TEST_STAGING_FRONTEGG_CLIENT_ID }}
          E2E_FRONTEGG_SECRET_KEY: ${{ secrets.E2E_TEST_STAGING_FRONTEGG_SECRET_KEY }}
        run: yarn test:e2e
      - run: docker ps -a
        if: always()
      - run: kubectl config get-contexts
        if: always()
      - run: kubectl config current-context
        if: always()
      - run: echo $KUBECONFIG
        if: always()
      - run: cat ~/.kube/config
        if: always()
      - name: bin/compose logs
        working-directory: ./cloud
        run: |
          for svc in $(bin/compose ps -a --services) ; do
            echo "::group::$svc"
            bin/compose logs -t $svc
            echo "::endgroup::"
          done
        if: always()
      - name: kubernetes logs
        run: |
          echo "::group::cockroachdb"
          kubectl --context kind-mzcloud logs -n cockroachdb --selector=app=cockroachdb --timestamps=true  --since=0s || true
          echo "::endgroup::"
        if: always()
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
        if: always()
